runtime: java
env : flex
inbound_services: 
- warmup
derived_file_type:
- java_precompiled
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"

runtime_config: 
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored
skip_files: app.yaml

resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1.0